require('dotenv').config();
const pool = require('./db');

async function main() {
  try {
    console.log('Altering nhan_vien vai_tro constraint...');
    // Drop constraint (requires knowing the constraint name, or we can just alter type if it's enum)
    // In PostgreSQL, to alter a CHECK constraint, we first drop it, then add the new one.
    // The default name generated by PostgreSQL is usually nhan_vien_vai_tro_check.
    await pool.query(`ALTER TABLE nhan_vien DROP CONSTRAINT IF EXISTS nhan_vien_vai_tro_check`);
    await pool.query(`ALTER TABLE nhan_vien ADD CONSTRAINT nhan_vien_vai_tro_check CHECK (vai_tro IN ('MANAGER', 'WAREHOUSE', 'SALES', 'ONLINE_SALES', 'MARKETING', 'CUSTOMER'))`);
    
    console.log('Success!');
  } catch (err) {
    console.error('Error:', err);
  } finally {
    await pool.end();
  }
}

main();
