-- Create database (optional)
-- CREATE DATABASE khang_baby CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE khang_baby;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  username VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL DEFAULT '',
  role ENUM('MANAGER','WAREHOUSE','SALES','ONLINE_SALES','MARKETING') NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  failed_attempts INT NOT NULL DEFAULT 0,
  locked_until DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  sku VARCHAR(20) PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT '',
  supplier VARCHAR(100) NOT NULL DEFAULT '',
  import_price DECIMAL(15,0) NOT NULL DEFAULT 0,
  sale_price DECIMAL(15,0) NOT NULL DEFAULT 0,
  min_stock INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipts (
  id VARCHAR(20) PRIMARY KEY,
  date DATE NOT NULL,
  supplier VARCHAR(100) NOT NULL,
  staff_id VARCHAR(10) NOT NULL,
  payment_id VARCHAR(20) NOT NULL DEFAULT '',
  order_id VARCHAR(20) NOT NULL DEFAULT '',
  qty_ordered INT NULL,
  qty_received INT NOT NULL DEFAULT 0,
  missing INT NOT NULL DEFAULT 0,
  status ENUM('PAID','UNPAID') NOT NULL DEFAULT 'UNPAID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_receipts_staff FOREIGN KEY (staff_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS receipt_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  receipt_id VARCHAR(20) NOT NULL,
  sku VARCHAR(20) NOT NULL,
  name VARCHAR(200) NOT NULL,
  price DECIMAL(15,0) NOT NULL DEFAULT 0,
  qty INT NOT NULL DEFAULT 0,
  mfg_date DATE NULL,
  exp_date DATE NULL,
  CONSTRAINT fk_receipt_items_receipt FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS batches (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_sku VARCHAR(20) NOT NULL,
  receipt_id VARCHAR(20) NOT NULL,
  received_date DATE NOT NULL,
  mfg_date DATE NULL,
  exp_date DATE NULL,
  qty_in INT NOT NULL,
  qty_remaining INT NOT NULL,
  import_price DECIMAL(15,0) NOT NULL DEFAULT 0,
  CONSTRAINT fk_batches_product FOREIGN KEY (product_sku) REFERENCES products(sku) ON DELETE CASCADE,
  CONSTRAINT fk_batches_receipt FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE,
  INDEX idx_batches_fifo (product_sku, received_date, id)
);

CREATE TABLE IF NOT EXISTS invoices (
  id VARCHAR(20) PRIMARY KEY,
  date DATETIME NOT NULL,
  staff_id VARCHAR(10) NOT NULL,
  customer VARCHAR(100) NOT NULL,
  voucher VARCHAR(50) NOT NULL DEFAULT '',
  payment_method VARCHAR(30) NOT NULL DEFAULT '',
  status ENUM('PAID','UNPAID','PENDING','CANCELED') NOT NULL DEFAULT 'UNPAID',
  total_items INT NOT NULL DEFAULT 0,
  total DECIMAL(15,0) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_invoices_staff FOREIGN KEY (staff_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  invoice_id VARCHAR(20) NOT NULL,
  sku VARCHAR(20) NOT NULL,
  name VARCHAR(200) NOT NULL,
  price DECIMAL(15,0) NOT NULL DEFAULT 0,
  qty INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(20) PRIMARY KEY,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  customer VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  address VARCHAR(255) NOT NULL,
  note TEXT NULL,
  channel ENUM('Facebook','Website','Zalo') NOT NULL DEFAULT 'Facebook',
  voucher VARCHAR(50) NOT NULL DEFAULT '',
  shipper VARCHAR(100) NOT NULL DEFAULT '',
  ship_fee DECIMAL(15,0) NOT NULL DEFAULT 0,
  eta DATE NULL,
  tracking VARCHAR(100) NOT NULL DEFAULT '',
  payment_method VARCHAR(30) NOT NULL DEFAULT 'COD',
  status ENUM('ChoXuLy','DangGiao','HoanThanh','HuyDon') NOT NULL DEFAULT 'ChoXuLy',
  staff_id VARCHAR(10) NOT NULL,
  total DECIMAL(15,0) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_staff FOREIGN KEY (staff_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id VARCHAR(20) NOT NULL,
  sku VARCHAR(20) NOT NULL,
  name VARCHAR(200) NOT NULL,
  price DECIMAL(15,0) NOT NULL DEFAULT 0,
  qty INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
